name: Deplofy

on: push

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: <azure subscription name>

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with soruce code
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Package 
        run: ./get-app-jar.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      # - name: deploy to production step with soruce code
      #   uses: azure/spring-cloud-deploy@v1
      #   with:
      #     azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
      #     action: deploy
      #     service-name: <service instance name>
      #     app-name: <app name>
      #     use-staging-deployment: false
      #     package: ${{ env.ASC_PACKAGE_PATH }}